### ISSUE TITLE
不支持中文路径

### ISSUE THREAD

**Issue by gaodyoffice** [z-henry/alist_storage_sync#2]
大佬，刚按配置说明试了，路径没中文正常，只要路径中有中文就报错。

**Comment by z-henry** [comment]
检查下config.json是不是utf8格式的

**Comment by gaodyoffice** [comment]
> 检查下config.json是不是utf8格式的

是的，UTF-8格式。

**Comment by z-henry** [comment]
一般windows默认读取文件格式为cp936。
已经修改为强制以utf8格式读取
